name: CI Pipeline

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/kaeyros-analytics/event-registration:latest
  CONTAINER_NAME_BACKEND: ucb__container

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u "${{ secrets.USERNAME }}" --password-stdin

      - name: Build the Docker image for backend
        run: |
          cd backend && \
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push backend image to GitHub Container Registry
        run: |
          docker push ${{ env.IMAGE_NAME }}
